# Generated by Django 6.1.1 on 2026-10-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_phone_number_credittransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'Top Up'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
