# Generated by Django 6.1.1 on 2026-10-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_credittransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
