# Generated by Django 6.1.1 on 2026-10-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
