# Generated by Django 6.1.1 on 2026-10-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_creatorwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorwithdrawal',
            name='callback_discrepancy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creatorwithdrawal',
            name='provider_failure_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorwithdrawal',
            name='provider_result_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorwithdrawal',
            name='refund_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creatorwithdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved_reserved', 'Approved and Reserved'), ('submitting', 'Submitting to Provider'), ('provider_pending', 'Provider Pending'), ('outcome_unknown', 'Outcome Unknown'), ('paid', 'Paid'), ('payout_failed_verified', 'Verified Payout Failure'), ('refunded', 'Refunded'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('outcome_unknown', 'Outcome Unknown'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
