# Generated by Django 6.1.1 on 2026-10-08 11:02

from django.db import migrations, models


def mark_existing_payout_outcomes_unknown(apps, schema_editor):
    Withdrawal = apps.get_model("payments", "CreatorWithdrawal")
    Withdrawal.objects.all().update(payout_status="legacy_unknown")


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_creatorwithdrawal_callback_discrepancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorwithdrawal',
            name='payout_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('legacy_unknown', 'Legacy Outcome Unknown'), ('submitting', 'Submitting'), ('provider_pending', 'Provider Pending'), ('outcome_unknown', 'Outcome Unknown'), ('paid', 'Paid'), ('payout_failed_verified', 'Verified Payout Failure')], default='not_submitted', max_length=32),
        ),
        migrations.RunPython(mark_existing_payout_outcomes_unknown, migrations.RunPython.noop),
    ]
